---
- name: Install Httpd Server in all below hosts 
  hosts: all
  become: true
  tasks: 
  - name: Install httpd server in below hosts
    yum: name=httpd  state=latest

  - name: create a directory
    file: path=/etc/Jenkins1 state=directory


